stages:
  load_data_sps:
    cmd: python -m src.data.load_data --all
    outs:
      - data/raw/experiments
      
  prepare:
    cmd: python3 src/features/prepare.py
    deps: 
    - src/features/prepare.py
    params: 
    - prepare.features
    outs:
    - data/prepared/

  
#  train:
#    cmd: python3 src/features/train.py
#    deps: 
#    - src/features/train.py
#    - data/prepared/train.csv
#    params: 
#    - prepare.features
 #   - prepare.features
 #   outs:
 #   - models/model.joblib


#  evaluate:
#    cmd: python3 src/features/evaluate.py
#    deps:
#    - data/prepared/test.csv
#    - models/model.joblib
#    params: 
#    - prepare.features
#    outs:
#    - models/results.json
