stages:
  load_data_sps:
    cmd: python -m src.data.load_data --id 1
    outs:
      - data/raw/experiments
  #load_data_helium:
  #  cmd: python -m helium_api_wrapper load-challenges --n 1000 --file_format "csv"
  #  outs:
  #    - data/raw/helium
      
  prepare:
    cmd: python3 src/features/prepare.py
    deps: 
    - src/features/prepare.py
    params: 
    - prepare.features
    outs:
    - data/prepared/

  

    

