stages:
  load_data_sps:
    cmd: python -m src.data.load_data --id 2
    outs:
      - data/raw/experiments
  #load_data_helium:
  #  cmd: python -m helium_api_wrapper load-challenges --n 1000 --file_format "csv"
  #  outs:
  #    - data/raw/helium
      
  prepare:
    cmd: python3 src/features/prepare.py
    deps: 
    - src/features/prepare.py
    params: 
    - prepare.features
    outs:
    - data/prepared/full_dataset.csv


  featurize:
    cmd: python3 src/features/featurize.py
    deps: 
    - data/prepared/full_dataset.csv
    params: 
    - prepare.features
    outs:
    - data/prepared/train.csv
    - data/prepared/test.csv

  
  train:
    cmd: python3 src/features/train.py
    deps: 
    - src/features/train.py
    - data/prepared/train.csv
    params: 
    - prepare.features
    - prepare.features
    outs:
    - models/model.joblib


  evaluate:
    cmd: python3 src/features/evaluate.py
    deps:
    - data/prepared/test.csv
    - models/model.joblib
    params: 
    - prepare.features
    outs:
    - models/results.json
