stages:
  prepare:
    cmd: python3 src/features/prepare.py
    deps: 
    - src/features/prepare.py
    params: 
    - prepare.features
    outs:
    - data/prepared
  crawl_data:
    cmd: python -m helium_api_wrapper load-challenges --n 10 --file_format "csv"
    outs:
      - data/raw/helium 

    #prepare:
    #cmd: python src/prepare.py
    #deps:
    #  - data/raw
    #  - src/prepare.py
    #outs:
    #  - data/prepared/test.csv
    #  - data/prepared/train.csv

