stages:
  load_data_sps:
    cmd: python -m src.data.load_data --all
    outs:
      - data/raw/sps/output_sps.csv
  load_data_helium:
    cmd: python -m helium_api_wrapper load-challenges --n 1000 --file_format "csv"
    outs:
      - data/raw/helium/output_helium.csv
      
  prepare:
    cmd: python3 src/features/prepare.py
    deps: 
    - src/features/prepare.py
    params: 
    - prepare.features
    outs:
    - data/prepared/train.csv
    - data/prepared/test.csv
  

    #prepare:
    #cmd: python src/prepare.py
    #deps:
    #  - data/raw
    #  - src/prepare.py
    #outs:
    #  - data/prepared/test.csv
    #  - data/prepared/train.csv

